CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  UID UUID NOT NULL,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL
);

CREATE TABLE CURRENCY (
  CODE VARCHAR(8) PRIMARY KEY
);

CREATE TABLE STOCK (
  CODE VARCHAR(8) PRIMARY KEY
);

CREATE TABLE USER_STOCKS (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  STOCK VARCHAR(8) NOT NULL,
  PRICE NUMERIC(19, 2) NOT NULL,
  CURRENCY VARCHAR(8) NOT NULL,
  QUANTITY INT NOT NULL,
  DEAL_TIME TIMESTAMP NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (STOCK) REFERENCES STOCK(CODE),
  FOREIGN KEY (CURRENCY)REFERENCES CURRENCY(CODE)
);


CREATE TABLE USER_FUNDS (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  VALUE NUMERIC(19, 2) NOT NULL,
  CURRENCY VARCHAR(8) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (CURRENCY) REFERENCES CURRENCY(CODE)
);
